### ISSUE TITLE
Which dominance rule is used in .bidirectional

### ISSUE THREAD

**Issue by MariaSKAF** [torressa/cspy#101]
Hello, i'm sorry for the simple question but i couldn't find it anywhere.
Which dominance rules are used in .bidirectional when direction==Forward?
Thanks in advance! :)

**Comment by torressa** [comment]
@MariaSKAF No worries it's all in 
https://github.com/torressa/cspy/blob/533af241ec3ff0e8ede97d084b7f5dd98d1b2a39/src/cc/labelling.cc#L162
Edge weight then resource comparison:
https://github.com/torressa/cspy/blob/533af241ec3ff0e8ede97d084b7f5dd98d1b2a39/src/cc/labelling.cc#L168-L190
Then elementary check:
https://github.com/torressa/cspy/blob/533af241ec3ff0e8ede97d084b7f5dd98d1b2a39/src/cc/labelling.cc#L206-L220
