### ISSUE TITLE
Are these algorithms can be used to find shortest path which travel through a set of specific nodes?

### ISSUE THREAD

**Issue by buhanfeng** [torressa/cspy#107]
Hi Torressa,

Are these algorithms can be used to find shortest path which travel through a set of specific nodes? If so, how can I set up the parameter? Thanks.

**Comment by torressa** [comment]
This is a different problem, there may be a way to hack around using resources but I'm not sure whether it would work or be efficient

**Comment by buhanfeng** [comment]
OK, thanks for your quick feedback, I will close the case.
