### ISSUE TITLE
What is an invertible REF?

### ISSUE THREAD

**Issue by glanch** [torressa/cspy#124]
Hello,

the documentation states about custom REFs that they need to be invertible. How would one check for such condition, given an REF? What does invertible REF even mean, formally spoken?

Best, glanch

**Comment by torressa** [comment]
These are required for traversing the graph in both directions. The formal definition and further discussion can be found in section 5 "Inversion of resource extension functions" from Irnich, S., 2008. Resource extension functions: Properties, inversion, and generalization to segments. OR Spectrum, 30(1), pp.113-148.

<img width="618" alt="Screenshot 2024-07-05 at 09 46 11" src="https://github.com/torressa/cspy/assets/23246013/f8c1b581-b898-4d7b-a57d-7cb9c6e9ef4b">
