### ISSUE TITLE
BiDirectional RCSPP solver: Resources on path being counted incorrectly

### ISSUE THREAD

**Issue by ericburrell-23-1** [torressa/cspy#126]
**Describe the bug**
I am using BiDirectional solver to solve an ERCSPP and am getting incorrect paths due to resource constraints being violated when they shouldn't be. Due to my use case I have some edges in the graph that use no resources (array of zeros) and I believe it is these edges that are being counted incorrectly.

**To Reproduce**
I have attached a .txt file of my Python code that provides a simple example that mimics my actual use case and demonstrates the issue.

**Expected behavior**
The resource consumption on the path should be less than the `problem.consumed_resources` value. I print the expected value at the end of the code execution.

**Desktop (please complete the following information):**
Microsoft Windows 11 Enterprise
Version 10.0.22000 Build 22000

**Suggestions**
I looked for the bug myself but no luck. Guessing it's in the C++ code.
[bidirec_resource_counting_failure_example.txt](https://github.com/user-attachments/files/18205168/bidirec_resource_counting_failure_example.txt)

**Comment by torressa** [comment]
Thanks! The first resource is not monotone: [Resource Extension Functions (REFs) - Pre-requirements](https://torressa.github.io/cspy/ref.html#pre-requirements), you can add this resource as the second one.

**Comment by ericburrell-23-1** [comment]
So a resource usage of zero on some edges make the resource no longer monotone? I would not have expected this to meet the definition of non-monotone.

I created an artificial, constantly increasing resource with infinite max and put my actual meaningful resource second. This appeared to work as intended. Thank you for the quick response.
