### ISSUE TITLE
Speed ups: BiDirectional

### ISSUE THREAD

**Issue by torressa** [torressa/cspy#37]
For some real cases, the BiDirectional algorithm is slow and sometimes stalls.

Here are some thing that can be done to speed things up.

## Dominance checks

- [ ] Rework `best_labels` so that dominance rules don't have to be applied twice.
- [x] Experiment with running full dominance checks at different frequencies
- [x] Apply the discarding property (non-elementary version was used in and every version prior to [v0.0.12](https://github.com/torressa/cspy/tree/v0.0.12))

### Frequency 

How often dominated labels are checked affects the algorithm, checking it after every iteration is probably not the best idea. 

### Discarding

In the non-elementary case, the dominated label and all of its extensions can be discarded, providing a significant speed up. In the elementary case a similar rule can be applied.
See [Irnich and Desaulniers (2005)](https://www.researchgate.net/profile/Stefan_Irnich2/publication/227142556_Shortest_Path_Problems_with_Resource_Constraints/links/0deec523898ae43b84000000.pdf) page 15.

## Stopping Early

If a threshold cost is given, the joining procedure can be stopped early if the resulting path has a total cost under the threshold. In the column generation setting, the threshold would be 0.

## C++

A possibility is to translate the algorithm into C++ and call it from python.

- [x] Do some research about interfacing C++ and python (should be alright)

## Parallel

I have a terrible implementation in parallel using  [``ray``](https://github.com/ray-project/ray) that works for some toy cases. However, as soon as you start passing custom REFs everything starts exploding. Even though I don't like the extra dependency it's pretty convenient as there are some shared arrays between the forward and backward processes. 

- [x] Commit to new `speedups` branch.

## Profiling

Some profiling with [line_profiler](https://github.com/pyutils/line_profiler) (cspy.BiDirectional) : 

~77% of the time is consumed by `self._algorithm(direct)`
![image](https://user-images.githubusercontent.com/19840033/79047070-c258a180-7c14-11ea-91bc-c3d92bb32cd0.png)

~50% consumed by `deque(map(self._propagate_label, edges, repeat(direc, len(edges))))`
~20% consumed by `self._check_dominance(next_label, direc)`
![image](https://user-images.githubusercontent.com/19840033/79047095-efa54f80-7c14-11ea-9661-07f6b0c25c8d.png)

- [x] Try for loop instead of `deque(map())`

_Originally posted by @Kuifje02 in https://github.com/Kuifje02/vrpy/issues/9#issuecomment-612439674_

**Comment by torressa** [comment]
I think it might be possible to parallelise the searches using ``ray``. It's a pretty big dependency though

**Comment by Kuifje02** [comment]
wow ! that is a brilliant idea. Would be very nice indeed !

**Comment by torressa** [comment]
Tried for-loop instead of `deque(map())` and is mostly faster.
