### ISSUE TITLE
jpath_preprocessing package missing

### ISSUE THREAD

**Issue by dymodi** [torressa/cspy#73]
jpath_preprocessing

**To Reproduce**
link: https://cspy.readthedocs.io/en/latest/how_to.html#simple-example
code: from jpath_preprocessing import relabel_source_sink, add_cspy_edge_attributes

**Expected behavior**
Clear description on how to use the package.

**Screenshots**
error: ModuleNotFoundError: No module named 'jpath_preprocessing'

**Comment by torressa** [comment]
Hey @dymodi 
The file `jpath_preprocessing.py` lives in [`examples/jpath/jpath_preprocessing.py`](https://github.com/torressa/cspy/blob/master/examples/jpath/jpath_preprocessing.py).

However, the callback REF in the notebook and the docs still uses the old syntax so needs updating. 
This has already been raised in #68
