### ISSUE TITLE
macOS 10.14: Can't install 1.0.0

### ISSUE THREAD

**Issue by juforg** [torressa/cspy#76]
**Describe the bug**
![image](https://user-images.githubusercontent.com/4046229/119868731-01999d00-bf52-11eb-9ed5-6e8af9880e42.png)

**Desktop (please complete the following information):**
 - OS: mac osx
 - Version 10.14.5 (18F2059)
Python 3.7.4

**Comment by torressa** [comment]
Hmm.. The wheel is definitely there for mac OS 10.15 + Python 3.7.

Before we try anything else, first can you try upgrading pip
```
pip install --upgrade pip
```

If that doesn't work can you try download the [cp37 wheel](https://files.pythonhosted.org/packages/6f/79/ab0ab6473ef516cd94981697da0f59a16132d1b75d325b2d29b6e76cb277/cspy-1.0.0-cp37-cp37m-macosx_10_15_x86_64.whl)
and installing directly
```
pip install cspy-1.0.0-cp37-cp37m-macosx_10_15_x86_64.whl
```

**Comment by juforg** [comment]
ERROR: cspy-1.0.0-cp37-cp37m-macosx_10_15_x86_64.whl is not a supported wheel on this platform.

**Comment by torressa** [comment]
Just added macos-10.14 to the release workflow but I think the minimum is 10.15 in github actions (https://github.com/torressa/cspy/runs/2716108521#step:1:4)

You're gonna have to build from source if you wan't to use this package as I don't have access to a macOS machine.
The dependencies are listed in the [README](https://github.com/torressa/cspy#locally) and once you have them installed you can do 

```bash
make python
pip install build/python/
```

**Comment by juforg** [comment]
ok, i will upgrade my macOS, but maybe you should add another version `macos-11`
https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
![image](https://user-images.githubusercontent.com/4046229/120341995-f5cf2180-c329-11eb-8ea8-54d740831ebb.png)

**Comment by torressa** [comment]
I've just tried that but as it says in the notice under that table they are not accepting any new `macos-11`
