### ISSUE TITLE
PSOLGENT fails when Source directly connected to Sink

### ISSUE THREAD

**Issue by dvbuntu** [torressa/cspy#79]
PSOLGENT has a check for prospective paths that demands they involve at least 3 nodes.  This misses the edge case where the Source has an edge connecting directly to the Sink.    Is this just a typo, and `len(path) >= 2` was intended?  Strictly speaking, even length 1 shouldn't throw an error, since one could access both `path[0]` and `path[-1]`, though obviously they can't both match.

https://github.com/torressa/cspy/blob/083f25c22d61ec2b5b2b1455839eb1e0a33f1e90/src/python/algorithms/psolgent.py#L333

**Comment by dvbuntu** [comment]
Looking through `psolgent.py` some more, would you mind if I put together a PR for this and other minor things (way nodes are sorted could break if `ZZ` is a node name, making position of source and sink node always "on", etc)?

**Comment by torressa** [comment]
Hey @dvbuntu Thanks for checking!
Great spot, that is a mistake.
Of course I'd be happy for a PR :)

**Comment by dvbuntu** [comment]
Hmm, is the setting of the lower and upper bound on the position values correct?  This is really only used during initialization, but the code now forces these to be U(0,1).  While the `sig` values are bounded this way, the actual positions are arbitrary reals.  Obviously there needs to be some reasonable bounds for initialization, but the PSOLGENT paper doesn't seem to describe what they used.

Maybe changing this to +-2 to make it symmetric and clear that the values are not necessarily bounded by 1 would be preferable?

https://github.com/torressa/cspy/blob/083f25c22d61ec2b5b2b1455839eb1e0a33f1e90/src/python/algorithms/psolgent.py#L138

**Comment by torressa** [comment]
The paper does specify for example the `rand` coefficients to be U(0,1), and the initialisation for the velocity to be zeros. 
Other than that I can't seem to find any info on the bounds.
I think I just used what I saw in a test in Solid (repo linked at the top of the file, test [here](https://github.com/100/Solid/blob/f38ca4906b7a253bfbb74f271229625d0f1df175/tests/test_particle_swarm.py#L13)) so as to avoid specifying lower/upper bounds for each problem.

My suspicion is that it will be may vary from problem to problem but I don't really understand what the implications/limitations.  
Maybe we could have some default values (`low=[0,..,0]`, `up=[1,..,1]`), but also let the user set them too.

**Comment by dvbuntu** [comment]
Default values with optional arguments sound good.  And I wrote to Dr. Marinakis from the PSOLGENT paper to see if he'll weigh in on what they used.

My understanding of PSO (and really most metaheuristics) is that ideally one covers the search space more or less uniformly with the initialization.  In the case of PSOLGENT, our search space is `R^n` for the positions (which when put the sigmoid become values in (0,1)).  We can't cover the whole thing uniformly, but I think an interval symmetric about zero is a good default.  Not a big deal either way since it will be specifiable.

**Comment by torressa** [comment]
Ahh that's a good shout!! Didn't think to do that... 
That makes sense! I think the velocity was U(-1,1)

**Comment by dvbuntu** [comment]
I like the way you have the velocities set with `U(lower-upper, upper-lower)`, but the paper I'm seeing initializes them to zero (last sentence of first paragraph of section 4), unless you mean for generic PSO.  Honestly probably doesn't make a big difference, and they don't necessarily describe why they choose these values anyway.  Do you think it's worth adding another parameter to enable zero initial velocity?  My inclination is no, but it's easy to add.
