### ISSUE TITLE
Label::checkDominance can break out if all_res_equal=false

### ISSUE THREAD

**Issue by mgalati13** [torressa/cspy#92]
This may not make a big performance difference, but it seems like after L167, when all_res_equal=false in 
https://github.com/torressa/cspy/blob/master/src/cc/labelling.cc

that you can break out of the loop, since all_res_equal can't be true at that point.

**Comment by mgalati13** [comment]
Another small improvement that might help is during that loop to flag if resource consumption is >. Then you can break out without going into another loop.

Something like this -- 

` bool rc_greaterThan = false;
  if (weight == other.weight) {
    // Check if all resources are equal
    bool all_res_equal = true;
    for (int i = 0; i < resource_size; i++) {
      if (resource_consumption[i] != other.resource_consumption[i]) {
         if(resource_consumption[i] > other.resource_consumption[i]){
            if(direction == bidirectional::FWD || i != c_res)
               rc_greaterThan = true;
         }
        all_res_equal = false;        
        //https://github.com/torressa/cspy/issues/92
        break;
      }
    }
    if (all_res_equal) {
      return false;
    }
  }
  // Compare weight
  if (weight > other.weight) {
    return false;
  }
  if(rc_greaterThan)
     return false;`

**Comment by mgalati13** [comment]
[issue92.txt](https://github.com/torressa/cspy/files/7876198/issue92.txt)

**Comment by torressa** [comment]
Hi @mgalati13! 
Thanks for reporting this. I have already changed this, waiting for some other changes for the next release https://github.com/torressa/cspy/blob/beb3cb829f3932bf07bf3951eb82aeba5a560a5d/src/cc/labelling.cc#L167-L173
