### ISSUE TITLE
lower bound 

### ISSUE THREAD

**Issue by mgalati13** [torressa/cspy#93]
Is there a way to calculate a lower bound on the objective value for CSP? 

In the case of stopping on time or threshold early, this can be useful in the context of a column generation algorithm (like in VRPY).

In addition, this might allow you to stop early if you have a valid path that is as low as your lower bound.

**Comment by torressa** [comment]
I don't think I know how to pre-compute a lower bound. One is kept on the fly for label pruning. I keep lower bounds from the shortest path problem, however this is not always very useful. 
https://github.com/torressa/cspy/blob/beb3cb829f3932bf07bf3951eb82aeba5a560a5d/src/cc/search.h#L31
Would be really interested if you founds / came up with something!

**Comment by soomin-woo** [comment]
Hi @torressa,

On a related note, I am computing the RMP objective function value (with linear relaxation) and the lagrangian lower bound.

![Node_0_Berkeley50_nocharger_BEVs_2022-03-03-22-00_ColGen_Progress](https://user-images.githubusercontent.com/69609930/157778832-cf88637f-0b2d-40cd-8ea4-cd2b74c2be35.png)

The blue curve is the RMP objective function value with linear relaxation.
The orange curve is the RMP objective function value with linear relaxation + the minimum reduced cost found in the iteration.

Note in the title of the figure, the "LB" is the RMP objective function value with linear relaxation, and the "UP" is the RMP objective function value without linear relaxation in the last iteration of the column generation. I always end the column generation by failing to find a route with a negative reduced cost.

Somehow, I can't seem to close the dual gap. 
The gap never converge 0 (it's always somewhere like 0.5 to 5% dual gap), although no route is found with a negative reduced cost.

Have you found this situation before?
Do you know if this is supposed to happen with a network with >= 30 nodes?

Thank you!

**Comment by mgalati13** [comment]
Without branching - there is no guarantee that you will close the gap.

**Comment by soomin-woo** [comment]
Hi @mgalati13,

Do you mean 'without branching' as in the branch-bound-and-price branching?
In that case, I don't agree but correct me if I'm wrong, please.

Column generation solves each subproblem at the branch and bound search tree, and it needs to close the gap between the RMP objective function (with linear relaxation) and the dual objective function to prove that it's solved at optimality. That's the only way you can get the lower bound at each branch and bound search tree. For a more detailed explanation, here's a great [video](https://youtu.be/vx2LNKx48vY?t=5334).

As the tree goes 'deeper', the lower bound at each node can remain the same or get worse. But the fact that you find a lower bound at each node means that you're at zero duality gap.
You need to close the duality gap at each node - no matter how many bounding constraints you have.

But please explain, why is there no guarantee that you will close the gap? Thank you.

**Comment by mgalati13** [comment]
I was assuming you were only doing the root node of branch-and-price. Yes, if you do full branch-and-price correctly, it should yield 0% gap eventually. How are you enforcing the branching? Note, I am talking about the integer gap. There is also the continuous gap in each B&B node.

As for your added comment, the bound is the RMP objective + the bounds from the subproblems. So, if you find no negative reduced cost columns, ignoring numeric issues, then the bounds from the subproblems should be 0, and you will have a 0% continuous gap.

**Comment by soomin-woo** [comment]
Hello @mgalati13! Yes, thank you for your feedback! Hope to solve this branch and bound algorithm well :)

**Comment by mgalati13** [comment]
Without branching - there is no guarantee that you will close the gap.
